### ISSUE TITLE
Use Omnipay standard methods

### ISSUE THREAD

**Issue by sanderha** [addgod/omnipay-dibs-d2#1]
Hello,

It looks like this omnipay driver is not implemented 100% correct. In `GeneralRequest` on line 27 and line 100 it should use `getTransactionId()` (omnipay method) instead of `getOrderId()`. Otherwise it seems it wont work the same as other omnipay drivers, resulting in an error at payment window ("no order id").

**Comment by addgod** [comment]
This issue have not been fixed.
